[package]
name = "using-liquidswap"
version = "0.0.0"

[dependencies]
Liquidswap = { git = "https://github.com/ThalaLabs/liquidswap.git", rev = "1570509e746b6626264cb6e9c0c8371683253961" }
LiquidswapLP = { git = "https://github.com/pontem-network/liquidswap-lp.git", rev = "v0.4.4" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "1570509e746b6626264cb6e9c0c8371683253961" }

[addresses]
example = "_"
